# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Piston Consumer', 'verbose_name_plural': 'Piston Consumers'},
        ),
        migrations.AlterModelOptions(
            name='nonce',
            options={'verbose_name': 'Piston Nonce', 'verbose_name_plural': 'Piston Nonces'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Piston Token', 'verbose_name_plural': 'Piston Tokens'},
        ),
        migrations.AlterField(
            model_name='token',
            name='timestamp',
            field=models.IntegerField(default=1478439325L),
        ),
    ]
